module.exports = [
  { alt: "a_bat", url: "//a-bat.com/" },
  { alt: "Alteran Labs", url: "//alteranlabs.co.uk/" },
  { alt: "byte", url: "//bytebat.zone/" },
  { alt: "Caius Nocturne", url: "//nocturne.works/" },
  { alt: "Catbot", url: "//catbot-beeps.neocities.org/" },
  { alt: "Caylee Morris", url: "//caylee.dev/" },
  { alt: "Cendyne", url: "//cendyne.dev/" },
  { alt: "codl", url: "//www.codl.fr/" },
  { alt: "DarkOverord", url: "//darkoverord.info/" },
  { alt: "David Cox", url: "//dav-idc.com/" },
  {
    src: "/assets/images/buttons/dex_dragon.png",
    alt: "Dex the Dragon",
    url: "//dexthedragon.co.uk/",
  },
  {
    src: "/assets/images/buttons/dusty.gif",
    alt: "Dusty's Corner",
    url: "//chcl.se/",
  },
  { alt: "Eevee", url: "//eev.ee/" },
  { alt: "Electric Keet", url: "//electrickeet.com/" },
  {
    src: "/assets/images/buttons/finch.gif",
    alt: "Finch's Tales",
    url: "//finchtale.neocities.org/",
  },
  {
    src: "/assets/images/buttons/freeplay.gif",
    alt: "Freeplay",
    url: "//freeplay.floof.company/",
  },
  { alt: "Halley Starbun", url: "//halley.systems/" },
  { alt: "Harley Watson", url: "//lobi.to/" },
  { alt: "Harsh Browns", url: "//visitmy.website/" },
  { alt: "Ji'hyn", url: "//jihyn.com/" },
  {
    src: "/assets/images/buttons/kay_ohtie.webp",
    alt: "Kay Ohtie",
    url: "//coyotesin.space",
  },
  { alt: "Lewis Dorigo", url: "//dorigo.co/" },
  { alt: "Lupinia Studios", url: "//www.lupinia.net/" },
  { alt: "maple mavica syrup", url: "//maple.pet/" },
  {
    src: "/assets/images/buttons/nano.png",
    alt: "Nano",
    url: "//nano.lgbt/",
  },
  { alt: "Ninji", url: "//wuffs.org/" },
  {
    src: "/assets/images/buttons/niss.png",
    alt: "Niss",
    url: "//yummy.cricket/",
  },
  {
    src: "/assets/images/buttons/null_patch.png",
    alt: "Null Patch - a projects blog by a system",
    url: "//nullpat.ch/",
  },
  { alt: "Oliver Byford", url: "//obyford.com/" },
  { alt: "Owen Jones", url: "//owenis.online/" },
  {
    src: "/assets/images/buttons/pebble.gif",
    alt: "Pebble.pet",
    url: "//pebble.pet/",
  },
  {
    src: "/assets/images/buttons/pont.gif",
    alt: "Pont",
    url: "//pont.cool/",
  },
  { alt: "QuARC", url: "//quarc.neocities.org/" },
  { alt: "rabbithawk256", url: "//rabbithawk256.dev/" },
  { alt: "raccoon", url: "//www.raccoon.fun/" },
  { alt: "Romaric Pascal", url: "//romaricpascal.is/" },
  { alt: "SDF", url: "//sdf.me.uk" },
  {
    src: "/assets/images/buttons/sigmucron.png",
    alt: "Sigmucron",
    url: "//sigmucron.neocities.org/",
  },
  {
    src: "/assets/images/buttons/sirlan.png",
    alt: "Sirlan",
    url: "//dragon-vi.be/",
  },
  { alt: "Tenna", url: "//tenna.zip/" },
  {
    src: "/assets/images/buttons/tuxedodragon.gif",
    alt: "Tuxedo Dragon",
    url: "//tuxedodragon.art/",
  },
  {
    src: "/assets/images/buttons/ulhar.png",
    alt: "Ulhar",
    url: "//ulhar.neocities.org/",
  },
  { alt: "Vanita Barrett", url: "//vanitabarrett.co.uk/" },
  { alt: "Violet Procyon", url: "//violet.pm/" },
  {
    src: "/assets/images/buttons/zatzhing.gif",
    alt: "Zatzhing.me",
    url: "//zatzhing.me/",
  },
  { alt: "zephi", url: "//zephi.cc/" },
  {
    src: "/assets/images/buttons/david_garden.webp",
    alt: "david.garden",
    url: "//david.garden/",
  },
  {
    src: "/assets/images/buttons/cybird.gif",
    alt: "Cybird's Nest",
    url: "//cybird.nekoweb.org/",
  },
  {
    src: "/assets/images/buttons/alloyed.gif",
    alt: "Kit!",
    url: "//alloyed.me/",
  },
  { src: "/assets/images/buttons/jkap.gif", alt: "jkap", url: "//jkap.io/" },
  {
    src: "/assets/images/buttons/pivot.gif",
    alt: "Pivot",
    url: "//pivot.gay/",
  },
  { alt: "keeri", url: "//keeri.place/" },
  { alt: "ninee (0x9E01)", url: "//www.ninee.xyz/" },
  { src: "/assets/images/buttons/cabl.gif", alt: "Cabl", url: "//cabl.rodeo/" },
  {
    src: "/assets/images/buttons/two.png",
    alt: "two",
    url: "//twotwos.nekoweb.org/",
  },
  {
    src: "/assets/images/buttons/maff.png",
    alt: "maff.scot",
    url: "//maff.scot/",
  },
];
