// Create an array of all tags that have been generated by Eleventy.
const getAllTags = function (collection) {
  let tagSet = new Set();
  collection.getAll().forEach((item) => {
    (item.data.tags || []).forEach((tag) => tagSet.add(tag));
  });
  tagSet = filterCommonTags([...tagSet]);
  return tagSet.sort();
};

// Filter out common tags, such as those that apply to all pages on the site or
// all things in the blog collection.
const filterCommonTags = function (tags) {
  return (tags || []).filter(
    (tag) => ["all", "blog", "nav", "post", "posts"].indexOf(tag) === -1
  );
};

// Replaces spaces with hyphens. A stylistic choice.
const formatAsTag = function (tag) {
  return `#${tag.replace(" ", "-")}`;
};

module.exports = {
  getAllTags,
  filterCommonTags,
  formatAsTag,
};
